# Generated by Django 2.2.10 on 2020-11-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('result', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body', models.TextField(blank=True)),
                ('type_qstn', models.CharField(choices=[('T', 'Text'), ('O', 'One'), ('M', 'Multiple')], default='Text', max_length=100)),
                ('Results', models.ManyToManyField(blank=True, related_name='results', to='tests.Results')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('qstns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Questions')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
