# Generated by Django 2.2.10 on 2020-11-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20201115_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_date',
        ),
    ]
