# Generated by Django 2.2.10 on 2020-11-15 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20201115_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='qstns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.Questions'),
        ),
    ]
