# Generated by Django 2.2.10 on 2020-11-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20201115_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='qstns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tests.Questions'),
        ),
    ]
