# Generated by Django 2.2.10 on 2020-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20201116_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='slug',
        ),
        migrations.AddField(
            model_name='questions',
            name='poll_name',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
