# Generated by Django 2.2.10 on 2020-11-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20201116_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='qstns',
        ),
        migrations.AddField(
            model_name='poll',
            name='qstns',
            field=models.ManyToManyField(blank=True, related_name='questions', to='tests.Questions'),
        ),
    ]
