# Generated by Django 2.2.10 on 2020-11-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20201116_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
