# Generated by Django 2.2.10 on 2020-11-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20201116_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='slug',
        ),
        migrations.AddField(
            model_name='results',
            name='poll_name',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
