# Generated by Django 2.2.10 on 2020-11-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20201116_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='user',
            field=models.IntegerField(),
        ),
    ]
